### ISSUE TITLE
multiprocessing / queue control for PyWPS

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pywps#165] opened 2016-08-26 14:43 UTC
# Description

Study multiprocessing for pypws: multiprocessing, gevents, events

Usage of queue system: Celery 
# Environment
- operating system:
  Linux
- Python version:  2?, 3
- PyWPS version: 4.x
- source/distribution

**Comment by ldesousa** [comment] 2018-03-22 14:49
This is a duplicate of #237

**Closed by ldesousa** 2018-03-22 14:49 UTC
Labels: documentation
